# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37993170e5c514954b3a8ae0437e716ff440be9f509b0155bb3a93139855d7958a26a8ecf7b4b2bc28e11900c72904253fad173833feb5ceeb4ffdef9d0f0495

test:
  secret_key_base: 0ebec0f8d0d2b9b44eab98146792e69fdad1ec585dd452d5e3392e606fb33d37e5627a8d18e36dedbdece20afc9f7ef1126de0c6af042e96e36a26439766679d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
